= Store
:page-layout: hmrf

== Commercial Licenses Pricing

[cols="1,2,2,2", options="header"]
|===
| | Small, Royalty Free, +
Site License | Medium, Royalty Free, +
Site License | Enterprise, Royalty Free, +
Site License

| Additional Use Grant
3+| You may make use of the Licensed Work, including directly serving third parties, other than your employees and contractors, so that such third parties directly benefit from the features of the Licensed Work.

| Applicability:
| A company has *less* than 100 total individuals working as employees or contractors, *and less* than 1,000,000 USD total revenue in the prior tax year.
| A company has *less* than 1000 total individuals working as employees or contractors, *and less* than 10,000,000 USD total revenue in the prior tax year.
| A company has *more* than 1000 total individuals working as employees or contractors, *or more* than 10,000,000 USD total revenue in the prior tax year.

| Price:
| *120 USD* +
per legal entity, per year.
| *1,200 USD* +
per legal entity, per year.
| *12,000 USD* +
per legal entity, per year.

|===

== When Do You Need a Commercial License?

This is not an exhaustive list of cases, but just a few examples to illustrate the general rules. If you are not sure or simply feel confused, never hesitate to mailto:licensing@nt-rest.com[write us^].

* If you fingerprint a *third-party* devices, then you need a commercial license;
* If you fingerprint devices you own, then you do *not* need a commercial license;
* If you authenticate a *third-party*, then you need a commercial license;
* If you authenticate a person who is an employee or contractor, then you do *not* need a commercial license;
* If you print a document and a *third-party* is the final owner of the hard copy, then you need a commercial license;
* If you print a document and you are the final owner of the hard copy, then you do *not* need a commercial license;
* If you scan an image and a *third-party* is the initial owner of the document, then you need a commercial license.
* If you scan an image and you are the initial owner of the document, then you do *not* need a commercial license.

== Additional Notes

* If a company is operating for less than one year, we assume no total revenue in the prior tax year whatsoever.
* Number of partners, workstations, or customers does not affect the price.
* A child company cannot work under license of a parent company.